### ISSUE TITLE
model.load(219)

### ISSUE THREAD

**Issue by ucasiggcas** [manicman1999/StyleGAN-Keras#12]
hi,
I have the problem when I run stylegan.py
```
Traceback (most recent call last):
  File "stylegan.py", line 505, in <module>
    model.load(219)
  File "stylegan.py", line 491, in load
    self.GAN.G = self.loadModel("gen", num)
  File "stylegan.py", line 475, in loadModel
    mod.load_weights("Models/"+name+"_"+str(num)+".h5")
  File "D:\python\lib\site-packages\keras\engine\saving.py", line 458, in load_wrapper
    return load_function(*args, **kwargs)
  File "D:\python\lib\site-packages\keras\engine\network.py", line 1208, in load_weights
    with h5py.File(filepath, mode='r') as f:
  File "D:\python\lib\site-packages\h5py\_hl\files.py", line 394, in __init__
    swmr=swmr)
  File "D:\python\lib\site-packages\h5py\_hl\files.py", line 170, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 85, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = 'Models/gen_219.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
```
emm,this is my first step,
am I wrong ?
any advice or suggestion will be appreciated.
thx

**Comment by Tylersuard** [comment]
Same.  I loaded a different model, gen_101, and got a different error about the dimensions not matching up.

**Comment by ma-siddiqui** [comment]
Hi,

Same i am facing. it looks the weight file is missing.

**Comment by proyaev** [comment]
Hi!
The same problem. Please upload actual data
